<?php

namespace App\Repository;

use App\Entity\User;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserProviderInterface
{
	/**
	 * @param string $username
	 * @return bool|null|object
	 */
	public function loadUserByUsername($username)
	{
		$user = $this->findOneBy(['username' => $username]);

		if (!$user) {
			return false;
		}

		return $user;
	}

	/**
	 * @param UserInterface $user
	 * @return null|object
	 */
	public function refreshUser(UserInterface $user)
	{
		if (!$user instanceof User) {
			throw new UnsupportedUserException(sprintf("UserRepository::refreshUser()", $user));
		}

		return $this->loadUserByUsername($user->getUsername());
	}

	/**
	 * @param string $class
	 * @return bool
	 */
	public function supportsClass($class)
	{
		return $class === 'App\Entity\User';
	}
}
